repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
    - id: check-executables-have-shebangs
    - id: requirements-txt-fixer
    - id: check-added-large-files
      args: ['--maxkb=50000']
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: mixed-line-ending
      args: ['--fix=lf']

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    - id: rst-backticks
    - id: rst-directive-colons

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.18.0
    hooks:
    - id: blacken-docs
      name: Autoformat codes in docstrings with blacken-docs
      additional_dependencies: [black]
      args: [-t, py38, -l, "100"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      name: Check common misspellings in text files with codespell.

