version: 2

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-24.04
  tools:
    python: '3.13'

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
