name: hyriver
channels:
  - numba
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.10

  # HyRiver packages
  - async-retriever >=0.3.8
  - pygeoogc >=0.13.10
  - pygeoutils >=0.13.10
  - py3dep >=0.13.10
  - pynhd >=0.13.8
  - hydrosignatures >=0.1.1
  - pygeohydro >=0.13.8
  - pydaymet >=0.13.8
  - pynldas2 >=0.1.1

  # optional deps
  - bottleneck
  - numba
  - planetary-computer
  - pyogrio
  - pystac-client
  - richdem >=0.3.4