name: binder
channels:
  - conda-forge
  - nodefaults
dependencies:
  # pygeoogc deps
  - aiodns
  - aiohttp
  - brotlipy
  - chardet
  - cytoolz
  - defusedxml
  - nest-asyncio
  - orjson
  - owslib
  - pyproj
  - requests
  - setuptools
  - shapely
  - simplejson

  # pygeoutils deps
  - geopandas
  - netCDF4
  - rasterio
  - xarray

  # pynhd deps
  - networkx
  - pyarrow

  # pygeohydro deps
  - folium
  - lxml
  - matplotlib-base
  - openpyxl

  # hyriver stack
  - pygeoogc
  - pygeoutils
  - pynhd
  - py3dep
  - pygeohydro
  - pydaymet

  # other third-party deps for running example notebooks
  - pygeos
  - bottleneck
  - osmnx
  - descartes
  - cartopy
  - cmocean
  - mapclassify

