name: docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter_client
  - pandoc
  - pip
  - pip:
    - sphinxext-opengraph
    - nbsphinx
    - recommonmark
    - sphinx
    - sphinx-autoapi
    - sphinx-book-theme
    - sphinx-book-theme
    - sphinx-copybutton
    - sphinx-gallery
    - sphinx-design
    - sphinxcontrib-bibtex

