name: docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter_client
  - nbsphinx
  - nbsphinx-link
  - pygithub
  - recommonmark
  - sphinx
  - sphinx-autoapi
  - sphinx-book-theme
  - sphinx-book-theme
  - sphinx-copybutton
  - sphinx-gallery
  - sphinx-panels
  - sphinxcontrib-bibtex
  - pandoc
  - pip
  - pip:
    - sphinxext-opengraph

