name: Build Website

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set environment variables
      run: |-
        echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "CONDA_ENV_FILE=docs/environment.yml" >> $GITHUB_ENV
        echo "PYTHON_VERSION='3.10'" >> $GITHUB_ENV

    - name: Setup micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: ${{ env.CONDA_ENV_FILE }}
        environment-name: docs
        extra-specs: |
          python=${{ env.PYTHON_VERSION }}
        cache-env: true
        cache-env-key: "${{runner.os}}-${{runner.arch}}-py${{env.PYTHON_VERSION}}-${{env.TODAY}}-${{hashFiles(env.CONDA_ENV_FILE)}}"

    - name: Build the website
      run: make docs-ci

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        external_repository: hyriver/hyriver.github.io
        publish_dir: docs/build/html
